fix rtnetlink compilation
although https://github.com/little-dude/netlink/pull/203 and
https://github.com/little-dude/netlink/pull/202 had no direct
conflict, merging both broke rtnetlink:

```
 error[E0063]: missing field `replace` in initializer of `neighbour::add::NeighbourAddRequest`
  --> rtnetlink/src/neighbour/add.rs:58:9
   |
58 |         NeighbourAddRequest { handle, message }
   |         ^^^^^^^^^^^^^^^^^^^ missing `replace`
```